# Generated by Django 3.1.3 on 2022-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200, null=True)),
                ('contact_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
