# Generated by Django 3.1.3 on 2022-06-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('shipper_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
